vim.api.nvim_command("set langmap+=é/")
vim.api.nvim_command("set langmap+=É?")
vim.api.nvim_command("set langmap+=¸]")
vim.api.nvim_command("set langmap+=^[")
vim.api.nvim_command("set langmap+=`'")
